export enum Operation {
  START_CREATE_PROJECT = 'START_CREATE_PROJECT',
  END_CREATE_PROJECT = 'END_CREATE_PROJECT',
  START_IMPORT_LIBRARIES = 'START_IMPORT_LIBRARIES',
  END_IMPORT_LIBRARIES = 'END_IMPORT_LIBRARIES',
  START_COMPILE = 'START_COMPILE',
  END_COMPILE = 'END_COMPILE',
  START_RUN = 'START_RUN',
  END_RUN = 'END_RUN',
}
